environment: production
environmentCode:
name: aphw-ddi-documents
namespace: aphw-ddi
workstream: aphw-ddi
image: aphw-ddi-documents

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: aphw-ddi-documents-config-map

containerSecret:
  name: aphw-ddi-documents-container-secret
  type: Opaque

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

deployment:
  replicas: 1
  minReplicas: 1
  maxReplicas: 4
  cpuThreshold: 80
  memoryThreshold: 400Mi

container:
  requestMemory: 120Mi
  requestCpu: 100m
  limitMemory: 500Mi
  limitCpu: 200m
  port: 3000
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageAccountName: aphwddi
  messageQueueHost: namespace.servicebus.windows.net
  certificateRequestQueue: aphw-ddi-certificate-request
  notifyApiKey: notifyApiKey
  eventsTopicAddress: aphw-ddi-events

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

aadPodIdentity: true
