services:
  aphw-ddi-documents:
    build:
      context: .
      target: production
    image: aphw-ddi-documents
    container_name: aphw-ddi-documents
    environment:
      APPINSIGHTS_CLOUDROLE: aphw-ddi-documents-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      CERTIFICATE_REQUEST_QUEUE_ADDRESS: ${CERTIFICATE_REQUEST_QUEUE_ADDRESS:-aphw-ddi-certificate-request}${MESSAGE_QUEUE_SUFFIX}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:-changeme}
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-test}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-test}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-test}
      EVENTS_TOPIC_ADDRESS: ${EVENTS_TOPIC_ADDRESS:-aphw-ddi-events}${MESSAGE_QUEUE_SUFFIX}
