# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  aphw-ddi-documents:
    build:
      target: development
    image: aphw-ddi-documents-development
    container_name: aphw-ddi-documents-development
    ports:
      - "3008:3000"
      - "9238:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    environment:
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:-DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://aphw-ddi-documents-azurite:10000/devstoreaccount1;}
    depends_on:
      - aphw-ddi-documents-azurite

  aphw-ddi-documents-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "10000:10000"

volumes:
  azurite_data:
