{{- include "ffc-helm-library.container-config-map" (list . "aphw-ddi-documents.config-map") -}}
{{- define "aphw-ddi-documents.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  {{- if and (.Values.environmentCode) (not .Values.pr) }}
  CERTIFICATE_REQUEST_QUEUE_ADDRESS: {{ .Values.container.certificateRequestQueue }}-{{ .Values.environmentCode }}
  {{- else }}
  CERTIFICATE_REQUEST_QUEUE_ADDRESS: {{ .Values.container.certificateRequestQueue }}
  {{- end }}
{{- end -}}
